#!/bin/bash
set -e

# Wait for MariaDB to be ready
echo "Waiting for MariaDB to be ready..."
while ! mysqladmin ping -h"mariadb" --silent 2>/dev/null; do
    echo "MariaDB is not ready yet, waiting..."
    sleep 2
done
echo "MariaDB is ready!"

# Generate wp-config.php if it doesn't exist
if [ ! -f /var/www/html/wp-config.php ]; then
    echo "Generating wp-config.php..."
    
    cat > /var/www/html/wp-config.php << EOF
<?php
/**
 * WordPress Configuration File
 * Generated by setup script
 */

// Database settings from environment variables
define('DB_NAME', '${MYSQL_DATABASE}');
define('DB_USER', '${MYSQL_USER}');
define('DB_PASSWORD', '${MYSQL_PASSWORD}');
define('DB_HOST', 'mariadb:3306');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

// Authentication unique keys and salts
define('AUTH_KEY',         '$(openssl rand -base64 48)');
define('SECURE_AUTH_KEY',  '$(openssl rand -base64 48)');
define('LOGGED_IN_KEY',    '$(openssl rand -base64 48)');
define('NONCE_KEY',        '$(openssl rand -base64 48)');
define('AUTH_SALT',        '$(openssl rand -base64 48)');
define('SECURE_AUTH_SALT', '$(openssl rand -base64 48)');
define('LOGGED_IN_SALT',   '$(openssl rand -base64 48)');
define('NONCE_SALT',       '$(openssl rand -base64 48)');

// WordPress database table prefix
\$table_prefix = 'wp_';

// WordPress debugging mode
define('WP_DEBUG', false);

// Absolute path to the WordPress directory
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

// Sets up WordPress vars and included files
require_once ABSPATH . 'wp-settings.php';
EOF

    chown www-data:www-data /var/www/html/wp-config.php
    echo "wp-config.php generated successfully!"
fi

# Install WordPress using WP-CLI if not already installed
if [ -f /usr/local/bin/wp ]; then
    # Check if WordPress is already installed
    if ! su -s /bin/bash www-data -c "wp core is-installed --path=/var/www/html" 2>/dev/null; then
        echo "Installing WordPress..."
        su -s /bin/bash www-data -c "wp core install \
            --path=/var/www/html \
            --url=https://${DOMAIN_NAME} \
            --title='Inception WordPress' \
            --admin_user=${WP_ADMIN_USER} \
            --admin_password=${WP_ADMIN_PASSWORD} \
            --admin_email=${WP_ADMIN_EMAIL} \
            --skip-email"
        echo "WordPress installed successfully!"
        
        # Create a second user as required
        echo "Creating additional WordPress user..."
        su -s /bin/bash www-data -c "wp user create \
            --path=/var/www/html \
            wpeditor editor@${DOMAIN_NAME} \
            --role=editor \
            --user_pass=editor_password_123" 2>/dev/null || true
        echo "Additional user created!"
    else
        echo "WordPress is already installed."
    fi
fi

# Execute the main command (php-fpm)
exec "$@"
